config/routes.rb
Rails.application.routes.draw do
  root to: "vehicles#index"
  devise_for :users
  resources :vehicles
  resources :reserves, only: [:index, :new, :create, :show]

  # get   'reserves/reserve/:vehicle_id',  to: 'reserve#reserve', as: 'reserves_reserve'
  # get   'reserves/my_reserve/:document', to: 'reserve#index', as: 'reserves_my_reserve'
  # post  'reserves/reserve/:vehicle_id',  to: 'reserve#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reserve.rb
class Reserve < ApplicationRecord
  belongs_to :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  has_many :reserves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reserves_controller.rb
class ReservesController < ApplicationController
  def index
    @reserves = Reserve.where(document: params[:document])
  end

  def new
    @reserve = Reserve.new
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def create
    Reserve.create(reserve_params)
    flash[:notice] = 'Veiculo reservado com sucesso'
    redirect_to vehicles_path
  end

  private

  def reserve_params
    params.require(:reserve).permit(:vehicle_id, :cpf)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @vehicles = Vehicle.all
  end

  def new
    @vehicle = Vehicle.new
    @models = []
    load_brands
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
    load_brands
    @models = HTTParty.get("http://fipeapi.appspot.com/api/1/carros/veiculos/#{@vehicle.brand}.json").parsed_response
  end

  def create
    Vehicle.create(vehicle_params)
    redirect_to vehicles_path
  end

  def update
    @vehicle = Vehicle.find(params[:id])
 
    if @vehicle.update(vehicle_params)
      redirect_to vehicles_path
    else
      render 'edit'
    end
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:license_plate, :brand, :model, :year_model, :year_manufacture)
  end

  def load_brands
    @brands = HTTParty.get('http://fipeapi.appspot.com/api/1/carros/marcas.json').parsed_response
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
  <title>Hello, world!</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- Material Kit CSS -->
  <link href="<%= root_path %>packs/css/material-dashboard.css?v=2.1.2" rel="stylesheet" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white">
      <div class="logo">
        <a href="/" class="simple-text logo-mini">
          Ao3
        </a>
        <a href="/" class="simple-text logo-normal">
          Teste
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <% if current_user %>
            <li class="nav-item active  ">
              <a class="nav-link" href="<%= new_vehicle_path %>">
                <i class="material-icons">Cadastrar Veículo</i>
                <p>Cadastrar Veículo</p>
              </a>
            </li>
            
          <% end %>
          <!-- your sidebar here -->
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="javascript:;"></a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link" href="javascript:;" id="navbarDropdownProfile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="material-icons">person</i>
                  <p class="d-lg-none d-md-block">
                    Account
                  </p>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownProfile">
                  <% if current_user %>
                    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: 'dropdown-item'  %>
                  <% else %>
                    <a class="dropdown-item" href="<%= new_user_session_path %>">Login</a>
                  <% end %>
                </div>
              </li>
            </ul>
          </div>
          
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <% if notice %>
            <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="#">
                  Teste Leonardo
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, 
            <a href="#" target="_blank">Teste</a> Ao3
          </div>
          <!-- your footer here -->
        </div>
      </footer>
    </div>
  </div>
  <script src="/packs/js/core/jquery.min.js"></script>
  <script src="/packs/js/core/popper.min.js"></script>
  <script src="/packs/js/core/bootstrap-material-design.min.js"></script>
  <script src="/packs/js/material-dashboard.js?v=2.1.2" type="text/javascript"></script>
</body>

</html>

app/views/reserves/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Reservar</h4>
        <p class="card-category">Veiculo: <%= @vehicle.model %></p>
      </div>
      <div class="card-body">
        
        <%= form_with model: @reserve do |form| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <%= form.label :document, class: 'bmd-label-floating' %>
                <%= form.number_field :document, { class: 'form-control' } %>
                <%= form.hidden_field :vehicle_id, value: params[:vehicle_id] %>
              </div>
            </div>
          </div>
          <%= form.submit class: 'btn btn-primary pull-right' %>
          <div class="clearfix"></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/_form.html.erb
<%= form_with model: @vehicle do |form| %>
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <%= form.label :license_plate, class: 'bmd-label-floating' %>
                          <%= form.text_field :license_plate, class: 'form-control' %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= form.label :brand, class: 'bmd-label-floating' %>
                          <%= form.select :brand, @brands.collect { |b| [b['fipe_name'], b['id']] }, { include_blank: true }, { class: 'form-control' } %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= form.label :model, class: 'bmd-label-floating' %>
                          <%= form.select :model, @models.collect { |m| [m['fipe_name'], m['fipe_name']] }, { include_blank: true }, { class: 'form-control' } %>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= form.label :year_model, class: 'bmd-label-floating' %>
                          <%= form.number_field :year_model, { min: 1900, max: 2099, class: 'form-control' } %>
                        </div>
                      </div>
                      <div class="col-md-6">
                        <div class="form-group">
                          <%= form.label :year_manufacture, class: 'bmd-label-floating' %>
                          <%= form.number_field :year_manufacture, { min: 1900, max: 2099, class: 'form-control' } %>
                        </div>
                      </div>
                    </div>
                    <%= form.submit class: 'btn btn-primary pull-right' %>
                    <div class="clearfix"></div>
<% end %>

<%= javascript_pack_tag 'js_form_vehicle' %>

app/views/vehicles/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Editar veículo</h4>
        <p class="card-category">Preencha todos os dados</p>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/index.html.erb
<div class="col-md-12">
              <div class="card card-plain">
                <div class="card-header card-header-primary">
                  <h4 class="card-title mt-0"> Lista de veículos</h4>
                  <p class="card-category"> Reserve o seu</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                    <table class="table table-hover">
                      <thead class="">
                        <th>
                          ID
                        </th>
                        <th>
                          Placa
                        </th>
                        <th>
                          Veículo
                        </th>
                      </thead>
                      <tbody>
                        <% @vehicles.each do |vehicle| %>
                          <% next if Reserve.where(vehicle_id: vehicle.id).count > 0 %>
                          <tr>
                            <td><%= vehicle.id %></td>
                            <td><%= vehicle.license_plate %></td>
                            <td><%= vehicle.model %></td>
                            <td>
                              <% if current_user %>
                                <%= link_to 'Editar', edit_vehicle_path(vehicle) %>
                              <% else %>
                                <%= link_to 'Reservar', new_reserf_path(vehicle_id: vehicle.id) %>
                              <% end %>
                            </td>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>

app/views/vehicles/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Novo veículo</h4>
        <p class="card-category">Preencha todos os dados</p>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>